### ISSUE TITLE
推断报错

### ISSUE THREAD

**Issue by songbaiTalk** [ljynlp/W2NER#10]
size mismatch for predictor.biaffine.weight: copying a param with shape torch.Size([12, 513, 513]) from checkpoint, the shape in current model is torch.Size([6, 513, 513]).
        size mismatch for predictor.linear.weight: copying a param with shape torch.Size([12, 288]) from checkpoint, the shape in current model is torch.Size([6, 288]).
        size mismatch for predictor.linear.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([6]).

仅进行推断时，load model会报上述错误，求解～～

**Comment by ljynlp** [comment]
从报错信息上来看，保存的模型应该是有12个label类别，而代码中label数量设置为了6，导致了参数不匹配
