### ISSUE TITLE
中文数据集

### ISSUE THREAD

**Issue by starxiaoliu** [ljynlp/W2NER#101]

**Comment by yangyang567** [comment]
你好，请问你要到了吗？

**Comment by starxiaoliu** [comment]
我已经找到了，打扰您啦！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ljynlp/W2NER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ljynlp/W2NER] 中文数据集 (Issue #101)





 
你好，请问你要到了吗？

**Comment by yangyang567** [comment]
可以方便分享一下吗？我目前没有要到，十分感谢，我的邮箱：3237727168@qq.com

**Comment by yangyang567** [comment]
已收到，万分感谢

**Comment by zyk0405** [comment]
您好，请问方便分享给我一份吗？十分感谢，邮箱是zyk0405@163.com

**Comment by yangyang567** [comment]
已发送

**Comment by yrfmessi** [comment]
可以方便分享给我一份吗？十分感谢，邮箱是 13453987503@163.com

**Comment by yangyang567** [comment]
已发送

**Comment by wyr-lab** [comment]
可以方便分享给我一份吗？十分感谢，邮箱是2922588394@qq.com

**Comment by yy-copliot** [comment]
已发送,请查收

**Comment by trian1248** [comment]
方便给我一份吗？邮箱  1239233794@qq.com   万分感谢

**Comment by yy-copliot** [comment]
已发送,请查收

**Comment by wqw547243068** [comment]
wqw547243068@163.com, 感谢分享

**Comment by secret12138** [comment]
1738932623@qq.com 你好，刚接触类似处理，可以分享一下吗？前面是我的邮箱，感谢分享

**Comment by yy-copliot** [comment]
> 

已发送

**Comment by yy-copliot** [comment]
> [1738932623@qq.com](mailto:1738932623@qq.com)

已发送

**Comment by yy-copliot** [comment]
> [1738932623@qq.com](mailto:1738932623@qq.com) 你好，刚接触类似处理，可以分享一下吗？前面是我的邮箱，感谢分享

已发送

**Comment by wqw547243068** [comment]
谢谢 421471852@qq.com 和 yangyang2879@qq.com 贡献数据

**Comment by Mewral** [comment]
594361769@qq.com 可以分享一下吗，感谢！

**Comment by yy-copliot** [comment]
> [594361769@qq.com](mailto:594361769@qq.com) 可以分享一下吗，感谢！

已发送

**Comment by palacexu** [comment]
您好，可以方便分享一下吗？谢谢！我的邮箱是 [icchiang@qq.com](icchiang@qq.com)

**Comment by yy-copliot** [comment]
> 您好，可以方便分享一下吗？谢谢！我的邮箱是 [icchiang@qq.com](icchiang@qq.com)

已发送

**Comment by palacexu** [comment]
> > 您好，可以方便分享一下吗？谢谢！我的邮箱是 [icchiang@qq.com](icchiang@qq.com)
> 
> 已发送

@yy-copliot 收到啦，谢谢！

**Comment by zxw254470434** [comment]
您好，可以分享一下吗，我的邮箱是254470434@qq.com，万分感谢！！！

**Comment by atyyymy** [comment]
> 我已经找到了，打扰您啦！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ljynlp/W2NER" ***@***.***&gt;; 发送时间:&nbsp;2023年8月3日(星期四) 中午11:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ljynlp/W2NER] 中文数据集 (Issue #101) 你好，请问你要到了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


> 我已经找到了，打扰您啦！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ljynlp/W2NER" ***@***.***&gt;; 发送时间:&nbsp;2023年8月3日(星期四) 中午11:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ljynlp/W2NER] 中文数据集 (Issue #101) 你好，请问你要到了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，请问可以分享一下中文数据集吗，最近也在做相关方面的一些实验，我的邮箱是Q15503672638@163.com，万分感谢

**Comment by atyyymy** [comment]
可以分享一下数据集嘛，最近也在做相关方面的实验，我的邮箱是Q15503672638@163.com，万分感谢

**Comment by yy-copliot** [comment]
> Q15503672638@163.com

已发送

**Comment by yy-copliot** [comment]
> 254470434@qq.com

已发送

**Comment by zhangyipeng1** [comment]
可以麻烦您也分享一下数据集给我嘛，我的邮箱是1662467351@qq.com，万分感谢~

**Comment by yy-copliot** [comment]
> 可以麻烦您也分享一下数据集给我嘛，我的邮箱是[1662467351@qq.com](mailto:1662467351@qq.com)，万分感谢~

已发送

**Comment by lyy20** [comment]
可以麻烦您也分享一下数据集给我嘛，我的邮箱是[903538308@qq.com]万分感谢~

**Comment by yy-copliot** [comment]
> 可以麻烦您也分享一下数据集给我嘛，我的邮箱是[[903538308@qq.com](mailto:903538308@qq.com)]万分感谢~

已发送

**Comment by guanxichouqu** [comment]
> > 可以麻烦您也分享一下数据集给我嘛，我的邮箱是[[903538308@qq.com](mailto:903538308@qq.com)]万分感谢~
> 
> 已发送

1262075293@qq.com      能发我一份嘛 谢谢

**Comment by yy-copliot** [comment]
> > > 可以麻烦您也分享一下数据集给我嘛，我的邮箱是[[903538308@qq.com](mailto:903538308@qq.com)]万分感谢~
> > 
> > 
> > 已发送
> 
> [1262075293@qq.com](mailto:1262075293@qq.com) 能发我一份嘛 谢谢

已发送

**Comment by 943203037** [comment]
您好，请问可以分享一下处理好的数据集和相关的配置文件吗，最近也在做相关方面的一些实验，我的邮箱是[[943203037@qq.com](mailto:943203037@qq.com)]万分感谢~

**Comment by innerVoi** [comment]
您好，我目前也想对上述中文数据集进行复现，请问可以分享一下数据集和相关的配置文件吗，十分感谢。我的邮箱是：954430845@qq.com

**Comment by yy-copliot** [comment]
> 您好，我目前也想对上述中文数据集进行复现，请问可以分享一下数据集和相关的配置文件吗，十分感谢。我的邮箱是：[954430845@qq.com](mailto:954430845@qq.com)

已发送

**Comment by Liuxwwa** [comment]
您好，我目前也想对论文中中文数据集进行复现，请问可以分享下数据集和相关的配置文件吗，非常感谢！我的邮箱是：1245583290@qq.com

**Comment by KekeWa** [comment]
997812140@qq.com可以分享一下吗，感谢！

**Comment by hsy-byte** [comment]
可以方便分享给我一份吗？十分感谢，邮箱是752040517@qq.com

**Comment by study-more-more** [comment]
> 752040517@qq.com
已发送

**Comment by study-more-more** [comment]
> [997812140@qq.com](mailto:997812140@qq.com)可以分享一下吗，感谢！

已发送

**Comment by study-more-more** [comment]
> 您好，我目前也想对论文中中文数据集进行复现，请问可以分享下数据集和相关的配置文件吗，非常感谢！我的邮箱是：[1245583290@qq.com](mailto:1245583290@qq.com)
已发送

**Comment by starxiaoliu** [comment]
> 您好，我刚接触，想在中文MSRA、OntoNotes 4.0和微博数据集上复现一下，能提供一下处理好的数据集和相关的配置文件吗，麻烦您啦，谢谢，我的邮箱：[421471852@qq.com](mailto:421471852@qq.com)

**Comment by scadule** [comment]
您好，请问可以方便共享一份中文数据集吗，万分感谢。我的邮箱是2177244381@qq.com

**Comment by guanxichouqu** [comment]
你好，我也是刚入门，请问一下你实现了吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ljynlp/W2NER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ljynlp/W2NER] 中文数据集 (Issue #101)





  
您好，我刚接触，想在中文MSRA、OntoNotes ***@***.***

**Comment by starxiaoliu** [comment]
复现了 &nbsp;


。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月1日(星期五) 下午2:40
收件人: "ljynlp/W2NER";
抄送: "State&nbsp;change";
主题: Re: [ljynlp/W2NER] 中文数据集 (Issue #101)





 你好，我也是刚入门，请问一下你实现了吗 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        &quot;ljynlp/W2NER&quot;                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月16日(星期四) 上午10:28 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ljynlp/W2NER] 中文数据集 (Issue #101) 
 
 
 
 
 
    
 您好，我刚接触，想在中文MSRA、OntoNotes ***@***.*** 
    
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
&mdash;

**Comment by cccjjjfff6** [comment]
2511106335@qq.com可以分享一下吗，谢谢！

**Comment by ghost** [comment]
楼上的兄弟方便分享一份给我吗   邮箱 nash1225@163.com  谢谢各位大佬

**Comment by yangyang567** [comment]
> 楼上的兄弟方便分享一份给我吗 邮箱 [nash1225@163.com](mailto:nash1225@163.com) 谢谢各位大佬

已发

**Comment by yangyang567** [comment]
> [2511106335@qq.com](mailto:2511106335@qq.com)可以分享一下吗，谢谢！

已发
