### ISSUE TITLE
gpu显存占用问题

### ISSUE THREAD

**Issue by ZiteHe** [ljynlp/W2NER#11]
在训练时只能设置batch_size  =4，无法进行大batch训练
在跑trainer.trian()时：
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:3C:00.0 Off |                    0 |
| N/A   55C    P0    77W /  70W |   6330MiB / 15109MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
跑到trainer.eval()时：
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:3C:00.0 Off |                    0 |
| N/A   71C    P0    71W /  70W |  12748MiB / 15109MiB |     92%      Default |
+-------------------------------+----------------------+----------------------+
显存占用会翻倍，并且不会在eval和test结束后释放，这导致无法使用大batch_size进行训练，不知道你们在跑的时候是不是也有这种情况，我看你们给出的至少都是batch_size=8以上

**Comment by ljynlp** [comment]
我们在训练时并没有遇到过显存占用在eval和test结束后不释放的问题，可以检查一下是否是验证集中有过长的样本导致的显存占用过大。
W2NER的一个缺点就是比较耗显存，我们是在24G的3090和32G的V100上进行实验的，如果出现显存不够用的问题，可以考虑以下几个方案，但是效果不能作保证：
* 混合精度
* 梯度累加
* 截短输入数据
* 降低conv_hid_size

希望能够帮到你

**Comment by ZiteHe** [comment]
谢谢，我再问一下，你们对于outputs的后处理有用到什么方法吗？还是就是直接按照论文写的对outputs[batch_size, L, L, label_num]处理一下就行了？

**Comment by ljynlp** [comment]
> 谢谢，我再问一下，你们对于outputs的后处理有用到什么方法吗？还是就是直接按照论文写的对outputs[batch_size, L, L, label_num]处理一下就行了？

这个后处理具体指什么呢？

**Comment by ZiteHe** [comment]
就是在做预测的时候，在decode里面是根据head_dict来提取出entity sequence的，对于有些entity，它的NNW标签是有被完整地预测出来（forward_dict是有序列的），但是它对应的类别标签没有被预测出来（ht_type_dict没有对应的label值），这个时候这个预测出来的序列就没法被提取出来了，对于这种情况有加入一些其他的处理技巧吗？谢谢

**Comment by ljynlp** [comment]
这个是没有的，如果类型没有预测出来的话就不算预测出entity。
