### ISSUE TITLE
中文数据集及配置文件

### ISSUE THREAD

**Issue by scadule** [ljynlp/W2NER#110]
您好，我想复现一下中文MSRA、OntoNotes 4.0和Weibo数据集上结果，能否提供一下相关的config文件，谢谢。
这是我的邮箱：2177244381@qq.com

**Comment by ghost** [comment]
楼上的兄弟有复现的效果吗？  我也想要一份中文数据集的config文件，能否提供一下，邮箱 nash1225@163.com ，谢谢！
