### ISSUE TITLE
每次复现分数有差别

### ISSUE THREAD

**Issue by 943203037** [ljynlp/W2NER#120]
请问，为什么不改变配置和数据集，但每次运行后得到的分数会不同？应该怎么设置才会相同呢？

**Comment by jack9193** [comment]
> 请问，为什么不改变配置和数据集，但每次运行后得到的分数会不同？应该怎么设置才会相同呢？

请问您找到随机性的源头了嘛，我最近复现模型也发现了这个问题，原封不动的代码跑2次结果不一致。
