### ISSUE TITLE
关于论文中dis_embedding的实现dist_inputs的疑问

### ISSUE THREAD

**Issue by HUSTHY** [ljynlp/W2NER#17]
代码中的dist_inputs有点不太理解作者为什么要这样子设计？
`        for k in range(length):
            _dist_inputs[k, :] += k
            _dist_inputs[:, k] -= k

        for i in range(length):
            for j in range(length):
                if _dist_inputs[i, j] < 0:
                    _dist_inputs[i, j] = dis2idx[-_dist_inputs[i, j]] + 9
                else:
                    _dist_inputs[i, j] = dis2idx[_dist_inputs[i, j]]
        _dist_inputs[_dist_inputs == 0] = 19`
_dist_inputs 为何还要减去dis2idx？以及dis2idx的值为何是这样子的：
`dis2idx = np.zeros((1000), dtype='int64')
dis2idx[1] = 1
dis2idx[2:] = 2
dis2idx[4:] = 3
dis2idx[8:] = 4
dis2idx[16:] = 5
dis2idx[32:] = 6
dis2idx[64:] = 7
dis2idx[128:] = 8
dis2idx[256:] = 9`

这个代码的作用有点不理解，请教一下作者？这样设计有什么深意吗？

**Comment by ljynlp** [comment]
我们的distance embedding是从[DocRED: A Large-Scale Document-Level Relation Extraction Dataset](https://aclanthology.org/P19-1074.pdf)借鉴的。

对于dis2idx的初始化，不同范围的相对距离(| i-j |)有对应的id，即id0对应距离[0]，id1对应距离[1]，id2对应距离[2-3]，id3对应距离[4-7]，id4对应距离[8-15]，以此类推。

```
        for k in range(length):
            _dist_inputs[k, :] += k
            _dist_inputs[:, k] -= k
```
这一步用于计算两个词之间的相对距离，即_dist_inputs[i, j]中i与j的相对距离。

```
        for i in range(length):
            for j in range(length):
                if _dist_inputs[i, j] < 0:
                    _dist_inputs[i, j] = dis2idx[-_dist_inputs[i, j]] + 9
                else:
                    _dist_inputs[i, j] = dis2idx[_dist_inputs[i, j]]
```
这一步将不同的距离转化为对应的id，如果_dist_inputs[i, j]为负，则将对应的id偏移9个单位。

总的来说，我们使用19个index来表示不同的相对距离，1-9表示i<j时的不同距离，10-18表示i>j时的不同距离，19表示i=j的情况。

**Comment by HUSTHY** [comment]
已收到！谢谢！                          ——黄洋

**Comment by HUSTHY** [comment]
谢谢  你的回复  已经理解了你们这里的dis_embedding为何要这设计和实现了；这么设计的好处不理解不懂，应该在你提到的那篇论文中，我去读一下；另外我也尝试一下 就是用：
`for k in range(length):
            _dist_inputs[k, :] += k`
上三角为负值，修改为绝对值，看看这样的dis_embedding在最后的结果上有什么差异变化没有。。。

**Comment by HUSTHY** [comment]
作者你好，你们有没有对比过 dis_embedding不同的设计，做消融实验没有？
我在你的代码基础上，做了2版的修改，结果分别如下：
不修改：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9812 |   0.9716  | 0.9916 |
|   Entity   | 0.9630 |   0.9609  | 0.9650 |
+------------+--------+-----------+--------+
修改版一，不使用dis2idx，且距离为负的时候修改绝对值，代码如下：
`        for k in range(length):
            _dist_inputs[k, :] += k
            _dist_inputs[:, k] -= k
                 for i in range(length):
            for j in range(length):
                if _dist_inputs[i, j] < 0:
                    _dist_inputs[i, j] = -_dist_inputs[i, j]
`
结果：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9746 |   0.9614  | 0.9901 |
|   Entity   | 0.9607 |   0.9607  | 0.9607 |
+------------+--------+-----------+--------+
修改版二，使用dis2idx，距离为负的时候，修改为绝对值，然后再替换为dis2idx中的index
`
        for k in range(length):
            _dist_inputs[k, :] += k
            _dist_inputs[:, k] -= k

        for i in range(length):
            for j in range(length):
                if _dist_inputs[i, j] < 0:
                    _dist_inputs[i, j] = dis2idx[-_dist_inputs[i, j]]
                else:
                    _dist_inputs[i, j] = dis2idx[_dist_inputs[i, j]]
        _dist_inputs[_dist_inputs == 0] = 19
`
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9773 |   0.9644  | 0.9924 |
|   Entity   | 0.9641 |   0.9633  | 0.9650 |
+------------+--------+-----------+--------+

可以得出修改版二的结果最好，是不是可以理解这样的dis_embedding在上下三角对称的效果好些，不用做偏移更好？

另外训练参数均没有修改，完成采用代码config带的参数，我的结果还是和论文中Resume数据的结果有点偏差，这是为什么呢？

**Comment by HUSTHY** [comment]
我昨天做了一下实验，采用不同形式的dis_inputs
第一是你们设计的那种，结果：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9812 |   0.9716  | 0.9916 |
|   Entity   | 0.9630 |   0.9609  | 0.9650 |
+------------+--------+-----------+--------+
一个是直接采用绝对距离，不使用dis2idx，并且_dist_inputs[i, j]为负直接替换为其绝对值，结果：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9746 |   0.9614  | 0.9901 |
|   Entity   | 0.9607 |   0.9607  | 0.9607 |
+------------+--------+-----------+--------+
最后一种就是还是采用dis2idx，把绝对距离进行切分，但是二维矩阵不做上下三角的偏移，对称的这种
`for k in range(length):
            _dist_inputs[k, :] += k
            _dist_inputs[:, k] -= k
for i in range(length):
            for j in range(length):
                if _dist_inputs[i, j] < 0:
                    _dist_inputs[i, j] = dis2idx[-_dist_inputs[i, j]]
                else:
                    _dist_inputs[i, j] = dis2idx[_dist_inputs[i, j]]
`
结果是：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9762 |   0.9634  | 0.9918 |
|   Entity   | 0.9616 |   0.9625  | 0.9607 |
+------------+--------+-----------+--------+

还是你们设计的这种采用了dis2idx做绝对距离切分，且上下三角矩阵有差异(而不是对称的那种)效果最好
个人猜测推理是因为这样的设计，后面的reg_embedding才带有上下三角区分的信息(上下三角值不一样)，这样才使得模型整体性能略有提升？

**Comment by HUSTHY** [comment]
我昨天做了一下实验，采用不同形式的dis_inputs
第一是你们设计的那种，结果：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9812 |   0.9716  | 0.9916 |
|   Entity   | 0.9630 |   0.9609  | 0.9650 |
+------------+--------+-----------+--------+
一个是直接采用绝对距离，不使用dis2idx，并且_dist_inputs[i, j]为负直接替换为其绝对值，结果：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9746 |   0.9614  | 0.9901 |
|   Entity   | 0.9607 |   0.9607  | 0.9607 |
+------------+--------+-----------+--------+
最后一种就是还是采用dis2idx，把绝对距离进行切分，但是二维矩阵不做上下三角的偏移，对称的这种
`for k in range(length):
            _dist_inputs[k, :] += k
            _dist_inputs[:, k] -= k
for i in range(length):
            for j in range(length):
                if _dist_inputs[i, j] < 0:
                    _dist_inputs[i, j] = dis2idx[-_dist_inputs[i, j]]
                else:
                    _dist_inputs[i, j] = dis2idx[_dist_inputs[i, j]]
`
结果是：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9762 |   0.9634  | 0.9918 |
|   Entity   | 0.9616 |   0.9625  | 0.9607 |
+------------+--------+-----------+--------+

还是你们设计的这种采用了dis2idx做绝对距离切分，且上下三角矩阵有差异(而不是对称的那种)效果最好
个人猜测推理是因为这样的设计，后面的reg_embedding才带有上下三角区分的信息(上下三角值不一样)，这样才使得模型整体性能略有提升？

**Comment by ljynlp** [comment]
是的，分类时表格中的上下三角分别表示了不同类型的关系，所以需要模型有区分上下三角的能力。

**Comment by HUSTHY** [comment]
还要一个问题哈 我用的是你们提供的代码和默认参数训练的模型，得出的结果和论文上略有差异呀，这是为什么呀？随机种子也没有修改呀。。难道是机器的原因？
我跑的结果：
+------------+--------+-----------+--------+
| TEST Final | F1 | Precision | Recall |
+------------+--------+-----------+--------+
| Label | 0.9812 | 0.9716 | 0.9916 |
| Entity | 0.9630 | 0.9609 | 0.9650 |
+------------+--------+-----------+--------+
论文的结果：
+------------+--------+-----------+--------+
| TEST Final | F1 | Precision | Recall |
+------------+--------+-----------+--------+
| Entity | 96.65| 96.96 | 96.35 |
+------------+--------+-----------+--------+

论文的F1值比我跑的结果略高，跑的是Resume数据集哈

**Comment by ljynlp** [comment]
我们在实验时发现使用CNN后随机种子就不起效果了，所以在代码中并未对种子进行固定，随意实验结果和论文有差异可能也是随机性导致的。另外可以试试将weight_decay设为0.1。
最后附上我近期在Resume上跑的三次实验结果：
+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9772 |   0.9651  | 0.9916 |
|   Entity   | 0.9641 |   0.9650  | 0.9632 |
+------------+--------+-----------+--------+

+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9791 |   0.9685  | 0.9914 |
|   Entity   | 0.9665 |   0.9692  | 0.9638 |
+------------+--------+-----------+--------+

+------------+--------+-----------+--------+
| TEST Final |   F1   | Precision | Recall |
+------------+--------+-----------+--------+
|   Label    | 0.9754 |   0.9623  | 0.9911 |
|   Entity   | 0.9668 |   0.9692  | 0.9644 |
+------------+--------+-----------+--------+

**Comment by HUSTHY** [comment]
好的 谢谢作者的回复  了解了这里为何不一样了
