### ISSUE TITLE
预训练模型版本问题

### ISSUE THREAD

**Issue by lonePatient** [ljynlp/W2NER#2]
您好，在论文中提到d_h的参数为768 和1024，也就是对应bert-base和bert-large，不知道论文实验中的指标所使用的的模型版本是base还是large呢？所有数据集都相同的模型大小吗？

**Comment by ljynlp** [comment]
为了方便对比，我们使用的预训练模型大小与previous works一致，比如CoNLL03、ACE2004、ACE2005等使用了Bert-large，而在中文数据集和非连续实体识别数据集上则使用Bert-base

**Comment by lonePatient** [comment]
您好！ShARe 13/14数据申请，一直还没审批通过下载，能否请教下数据下载的问题，个人QQ:1436496575.

**Comment by ljynlp** [comment]
> > 为了方便对比，我们使用的预训练模型大小与previous works一致，比如CoNLL03、ACE2004、ACE2005等使用了Bert-large，而在中文数据集和非连续实体识别数据集上则使用Bert-base
> 
> 作者你好，我今天在复现代码的时候，发现日志中，在进行eval和test的时候，针对precision、recall和f1都会统计label和entity请问这个label和entity分别表示什么呢，希望能得到你的回复，

label指论文Section 2中所描述的word与word间的关系，在得到这些label后，需要根据Section 3 Decoding中的方式解码得到最终的entity
