### ISSUE TITLE
实体label如何学到的呢？

### ISSUE THREAD

**Issue by panxmay** [ljynlp/W2NER#29]
您好，我在阅读论文的时候有一点困惑：2d grid最后预测的关系为三种，通过解码可以得到不同的实体序列，但是如何得到实体类型呢？
我看预测的结果中会包含实体的类型，但在论文中没有看到是如何做到的，期待解答～

**Comment by ljynlp** [comment]
模型需要预测NNW和THW-*两种关系来解码对应的实体，*表示不同的实体类型，也就是说除了None和NNW外，模型还需要预测不同实体类型的THW，从而解码出不同类型的实体。

**Comment by panxmay** [comment]
懂啦！感谢~ 你们的工作真的好厉害！！！
