### ISSUE TITLE
Overlapped NER 和 Discontinuous NER中的F1的计算逻辑

### ISSUE THREAD

**Issue by YuhongLIN4131** [ljynlp/W2NER#30]
请问您在论文的figure 5中所展示的Overlapped NER 和 Discontinuous NER中的F1计算逻辑是什么，特别是其中的FP是如何计算的？

**Comment by ljynlp** [comment]
这块我们是使用模型分别在只标注overlapped entity和discontinuous entity的数据上进行训练和测试的

**Comment by YuhongLIN4131** [comment]
请问方便给一下ACE2004/2005的config文件嘛，我们按照conll03的config文件复现ACE2004/2005时，多次实验的最好结果还是比论文中给出的低1个点左右，请问是不是这两个数据集中的超参数设置有什么特别

**Comment by ljynlp** [comment]
不同于conll03，在ACE2004/2005的实验中我们使用了bert-large-cased版本

**Comment by ljynlp** [comment]
ACE2005 config文件已经上传

**Comment by YuhongLIN4131** [comment]
非常感谢您的回复！
