### ISSUE TITLE
关于显存占用逐渐增大的问题

### ISSUE THREAD

**Issue by hupidong** [ljynlp/W2NER#31]
你好，在实际使用的过程中发现显存占用逐渐增大。对于小数据集还好，但是对于很大的训练集，比如几十万个语句，即使batch_size=1也会出现CUDA_OUT_OF_MEMORY。定位发现应该是预测结果的累积导致的显存爆炸。

原代码：
 label_result.append(grid_labels)
 pred_result.append(outputs)

修改如下即可：
 label_result.append(grid_labels.cpu())
 pred_result.append(outputs.cpu())

**Comment by ljynlp** [comment]
感谢提醒bug，我们会对代码进行修改
