### ISSUE TITLE
关于中文数据集设置

### ISSUE THREAD

**Issue by Ch4osMy7h** [ljynlp/W2NER#39]
您好，我想复现一下中文MSRA、OntoNotes 4.0和Weibo数据集上结果，能否提供一下相关的config文件，这是我的邮箱：ch4osmy7h@gmail.com

**Comment by FalAnge1217** [comment]
> 

你好，能否分享一下这几个数据集呢？我的邮箱：2674053421@qq.com

**Comment by Guanghe-Lin** [comment]
同求，我的邮箱：guanghe.lin@qq.com
