### ISSUE TITLE
On dataset & processing codes

### ISSUE THREAD

**Issue by pocca2048** [ljynlp/W2NER#4]
Hi! Thank you for sharing your works!

Could you share your data processing codes?

Also, this [link](https://drive.google.com/drive/folders/1NdvUeIUUL3mlS8QwwnqM628gCK7_0yPv?usp=sharing) seems to require access rights. Could you change to sharable to everyone?

Thank you very much.

**Comment by ljynlp** [comment]
My co-authors can download the datasets in this link without any access rights, so I guess there is no problem with the link. The datasets we used are too many to reconstruct the data processing codes, you can process them to fit the same format as the examples.

**Comment by pocca2048** [comment]
Oh now i can access the link. Thank you.

**Comment by Fpw19980724** [comment]
> My co-authors can download the datasets in this link without any access rights, so I guess there is no problem with the link. The datasets we used are too many to reconstruct the data processing codes, you can process them to fit the same format as the examples.

你好，想问一下如果一个句子中并没有任何的命名实体的话，这个是怎么表示呢？我看到example中都是存在命名实体的表示

**Comment by ljynlp** [comment]
句子中没有抽出命名实体的话，输出的文件中的实体列表即为空。

**Comment by Fpw19980724** [comment]
> 句子中没有抽出命名实体的话，输出的文件中的实体列表即为空。

那对应的ner字段里的index和type填什么呢？还是"ner"后面直接赋一个空列表？如 {"sentence": ["x", "y"], "ner": []}

**Comment by ljynlp** [comment]
是的

**Comment by Fpw19980724** [comment]
> 是的，ner字段的list为空

Thx again~
