### ISSUE TITLE
torch.cat报错

### ISSUE THREAD

**Issue by Fpw19980724** [ljynlp/W2NER#41]
``Traceback (most recent call last):
  File "main.py", line 301, in <module>
    trainer.train(i, train_loader)
  File "main.py", line 77, in train
    label_result = torch.cat(label_result)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, Autograd, Profiler, Tracer, Autocast]

跑example demo的时候出了这个问题，代码没有改过，不知道大家有没有遇到过相同的问题，或者怎么去解决的呢？

**Comment by ljynlp** [comment]
你好，data中的example只是用来展示数据格式的，可以使用README第3节中提供的数据集来进行测试。

**Comment by Fpw19980724** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Fpw19980724** [comment]
> 你好，data中的example只是用来展示数据格式的，可以使用README第3节中提供的数据集来进行测试。

Thx, 使用按example格式调整自己的数据集也是可以的吧~

**Comment by ljynlp** [comment]
可以的

**Comment by Fpw19980724** [comment]
> 可以的

感谢啦~ 回复太及时啦~
