### ISSUE TITLE
在CMeEE数据上报错

### ISSUE THREAD

**Issue by FalAnge1217** [ljynlp/W2NER#44]
![5153b086f9b4871374eb7ac90d1e24b](https://user-images.githubusercontent.com/82627285/177454464-5e37ab3e-ffa8-4bd4-abaf-6e200b8a3b55.png)
debug后发现是 
`_dist_inputs[i, j] = dis2idx[-_dist_inputs[i, j]] + 9`
这一句这里出错了，不知道应该怎么修改
我的数据处理后如下，中英文混杂的把英文也拆成了单个字符，不知道这样处理对不对
![微信图片_20220706102257](https://user-images.githubusercontent.com/82627285/177454311-ffbd88f6-e3e7-4519-8d87-e243e7953caa.png)

**Comment by ljynlp** [comment]
应该是处理完后句子长度太长了，超过了设定的1000导致报错。如果句子里面英文单词过多的话不建议把单词拆成字母，不然句子很可能过长导致程序无法运行。

**Comment by ljynlp** [comment]
即使这里修改了，还是会超出BERT的512个token的限制，同样会报错，最好直接将超出长度的句子处理掉。

**Comment by FalAnge1217** [comment]
> 即使这里修改了，还是会超出BERT的512个token的限制，同样会报错，最好直接将超出长度的句子处理掉。
![微信截图_20220708213356](https://user-images.githubusercontent.com/82627285/178002529-b0d5c201-d1ad-4833-bc68-82667c0c1b15.png)
你好，句子长度大于500个token的我都处理掉了，又报新的越界错误，这怎么解决呢？是不是因为我数据集里面的实体类别比代码里面原来设定的类别数多的问题？

**Comment by ljynlp** [comment]
可能是你数据处理的有问题，最好查验一下每个样本中的实体index与对应文本中的内容是否一致。

**Comment by FalAnge1217** [comment]
> 可能是你数据处理的有问题，最好查验一下每个样本中的实体index与对应文本中的内容是否一致。
![微信截图_20220711154012](https://user-images.githubusercontent.com/82627285/178213466-c7145fcc-37d3-4f89-a05b-d8d8df9a7caa.png)
实体index与对应文本中的内容对得上，我发现更你提供的resume-zh数据集比我少加了world这个字段，我用得config文件还是resume-zh的，不知道是不是这个原因
