### ISSUE TITLE
预测结果中的实体并不是按顺序出现的

### ISSUE THREAD

**Issue by zhYua** [ljynlp/W2NER#45]
我用W2NER在自己数据集上进行预测后，出来的实体结果顺序并不是按照原始文本中的顺序，比如我的文本是ABC，但是预测的实体顺序是ACB这样，请问这个顺序是需要自己后处理调么，还是在inference的时候可以设置，或者是我 预测有问题

**Comment by ljynlp** [comment]
可以举一个具体的例子吗？

**Comment by zhYua** [comment]
比如：超逸三组调味盒，我想要的结果是超逸：品牌，三组：规格，调味盒：商品   但是现在预测出来的json文件中，不是按照超逸、三组、调味盒的顺序出现的，而是乱序
![image](https://user-images.githubusercontent.com/52768528/178921473-6ad8a529-ddff-4773-869a-44f94562957a.png)

**Comment by ljynlp** [comment]
我们在解码的时候为了处理可能存在的重复抽取的情况，使用了set对结果进行了去重，因此不能保证结果的顺序，如果需要可以自行根据实体的位置进行排序。

**Comment by zhYua** [comment]
那请问解码时候有输出实体头尾位置的这个返回值么

**Comment by ljynlp** [comment]
输出结果并没有实体的位置信息，具体可以在`utils.py`中的`decode()`中进行修改。

**Comment by zhYua** [comment]
好的，谢谢
