### ISSUE TITLE
自定义数据集训练出问题

### ISSUE THREAD

**Issue by aph-asic** [ljynlp/W2NER#49]
![Dingtalk_20220725182552](https://user-images.githubusercontent.com/54587975/180756057-36f1ce33-0c24-4ca1-a5ea-3b885a351f3f.jpg)
出现zg这个问题是不是因为我数据集中的文本长度过长呢，该怎么解决呢，望解答！！！

**Comment by ljynlp** [comment]
文本过长了，可以看看有没有bert tokenize后长度超过512的case，这些case可能需要分段处理

**Comment by aph-asic** [comment]
还有个问题就是，请问这个算法能解决嵌套实体任务吗

**Comment by aph-asic** [comment]
还有个问题就是，请问这个算法能解决嵌套实体任务吗

**Comment by ljynlp** [comment]
可以的，细节在论文里可以看到
