### ISSUE TITLE
关于数据集ace2004/2005的超参数设置

### ISSUE THREAD

**Issue by YuhongLIN4131** [ljynlp/W2NER#5]
请问能给出ace2004/2005的超参数设置嘛，我们的按照conll03的参数设置复现ace数据集时，发现最终的结果差距较大，不知道是不是超参数的选择上有什么变动

**Comment by starxiaoliu** [comment]
> 

你好，如果方便的话，有关ace2004/2005的数据集可以分享一下么，我的邮箱421471852@qq.com，谢谢啦！

**Comment by starxiaoliu** [comment]
> 请问能给出ace2004/2005的超参数设置嘛，我们的conll03的参数设置复现ace数据集时，发现最终的结果差距扩大，不知道是不是超参数的选择上有什么波动
你好，如果方便的话，有关ace2004/2005的数据集可以分享一下么，我的邮箱[421471852@qq.com](mailto:421471852@qq.com)，谢谢啦！

**Comment by starxiaoliu** [comment]
> 请问能给出ace2004/2005的超参数设置嘛，我们的按照conll03的参数设置复现ace数据集时，发现最终的结果差距较大，不知道是不是超参数的选择上有什么变动
你好，如果方便的话，有关ace2004/2005的数据集可以分享一下么，我的邮箱[421471852@qq.com](mailto:421471852@qq.com)，谢谢啦！
