### ISSUE TITLE
有关中文数据集字段的问题

### ISSUE THREAD

**Issue by Luxueux** [ljynlp/W2NER#50]
您好，在resume数据集文件里有一个word关键字类似于分词的，但是我好像没有在代码中看到哪里使用了它。请问这个关键字是否是必须的，如果是它是如何获得的呢？

期待您的回复

**Comment by ljynlp** [comment]
这个字段存储针对中文文本分词的结果，但实际上我们为了保证中英文数据集实验的一致性并没有用到该字段，可以忽略

**Comment by Luxueux** [comment]
> 

好的了解了，非常感谢
