### ISSUE TITLE
中文数据集复现配置问题

### ISSUE THREAD

**Issue by Kathrine94** [ljynlp/W2NER#51]
您好，我想复现一下中文MSRA、OntoNotes 4.0和Weibo数据集上结果，能否提供一下相关的config文件，谢谢。
这是我的邮箱：947764325@qq.com

**Comment by Kathrine94** [comment]
大佬，我目前用自己配置的参数在MSRA、OntoNotes 4.0和Weibo上的结果不是很好，应该是某些参数没配好，可否麻烦共享一下相关的配置，不胜感激。947764325@qq.com

**Comment by ljynlp** [comment]
邮件已发送，请注意查收

**Comment by szj2ys** [comment]
您好，我想复现一下中文MSRA、OntoNotes 4.0和Weibo数据集上结果，能否提供一下相关的config文件，谢谢。
这是我的邮箱：15574364821@163.com

**Comment by minskiter** [comment]
您好，我想复现一下中文MSRA、OntoNotes 4.0和weibo数据集上结果，使用RESUME的配置效果不佳，能否提供一下相关的config文件，谢谢。
这是我的邮箱：[minskiter@qq.com](mailto:minskiter@qq.com)

**Comment by hsy-byte** [comment]
> 您好，我想复现一下中文MSRA、OntoNotes 4.0和Weibo数据集上结果，能否提供一下相关的config文件，谢谢。 这是我的邮箱：[947764325@qq.com](mailto:947764325@qq.com)
可以发给我一下中文MSRA、OntoNotes 4.0和Weibo数据集相关的config文件，想要复现一下，谢谢。
这是我的邮箱：752040517@qq.com
