### ISSUE TITLE
自定义数据并训练时出现”RuntimeError: input.size(-1) must be equal to input_size. Expected 768, got 1024.“怎么处理哇？感谢你

### ISSUE THREAD

**Issue by Shajiu** [ljynlp/W2NER#52]
自定义数据并训练时出现”RuntimeError: input.size(-1) must be equal to input_size. Expected 768, got 1024.“怎么处理哇？感谢你

**Comment by ljynlp** [comment]
可能是BERT的输出维度和LSTM的输入维度不一致造成的，可以在配置文件里修改一下

**Comment by Shajiu** [comment]
好的，谢谢你，可以了，但是当模型保存后如何再次加载模型并推理的脚本你有么？方便发么？

**Comment by ljynlp** [comment]
这个没有写，需要自己实现一下

**Comment by ucas010** [comment]
> 好的，谢谢你，可以了，但是当模型保存后如何再次加载模型并推理的脚本你有么？方便发么？

同求啊。

**Comment by YJSoooooo** [comment]
> 自定义数据并训练时出现”RuntimeError: input.size(-1) must be equal to input_size. Expected 768, got 1024.“怎么处理哇？感谢你



> 好的，谢谢你，可以了，但是当模型保存后如何再次加载模型并推理的脚本你有么？方便发么？

你好你好 我也遇到和你同样的问题 我想问一下您当时具体改了那些参数 谢谢大佬
