### ISSUE TITLE
关于utils.py

### ISSUE THREAD

**Issue by 2020lwh567** [ljynlp/W2NER#54]
你好，我看到utils.py换成了deque实现，想问一下之前这种实现方法是有什么缺陷嘛
![image](https://user-images.githubusercontent.com/73807088/185423370-cc906391-fd3b-40a4-b578-011e5b3fe798.png)

**Comment by ljynlp** [comment]
提升一些解码效率，具体可见https://github.com/ljynlp/W2NER/pull/38#issue-1264281937
