### ISSUE TITLE
您好，我想问一下，如何将普通的BIO形式的数据集，转化成您用到的json形式的数据集呀

### ISSUE THREAD

**Issue by zyx214** [ljynlp/W2NER#60]

**Comment by nlper01** [comment]
> _No description provided._

请问你解决了吗？

**Comment by qinglongheu** [comment]
请问你解决了吗？

**Comment by nlper01** [comment]
FalAnge
***@***.***



Tongjilibo 实现的W2NER中直接用BIO格式数据加载，你可以参考参考。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ljynlp/W2NER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ljynlp/W2NER] 您好，我想问一下，如何将普通的BIO形式的数据集，转化成您用到的json形式的数据集呀 (Issue #60)





 
请问你解决了吗？
