### ISSUE TITLE
中文数据集

### ISSUE THREAD

**Issue by zyx214** [ljynlp/W2NER#62]
您好，我刚刚接触NER，想在中文MSRA、OntoNotes 4.0和Weibo数据集上复现一下，可以提供一下处理好的数据集和相关的config文件吗，麻烦您啦，谢谢，我的邮箱：979829128@qq.com

**Comment by wind1312** [comment]
我也想知道在哪下载，请问能给一份吗，我的邮箱：1132281287@qq.com
