### ISSUE TITLE
关于biaffine classifier

### ISSUE THREAD

**Issue by jingsongs** [ljynlp/W2NER#64]
您好！
       论文中用到的 biaffine classifier，公式如下，这里的W[si; oj ]是指什么？ 另外代码的具体实现和公式是怎么对应的？
       
![image](https://user-images.githubusercontent.com/25786748/189024884-6abd8116-769f-4687-994f-7f52b02b9a5e.png)

        if self.bias_x:
            x = torch.cat((x, torch.ones_like(x[..., :1])), -1)
        if self.bias_y:
            y = torch.cat((y, torch.ones_like(y[..., :1])), -1)
        # [batch_size, n_out, seq_len, seq_len]
        s = torch.einsum('bxi,oij,byj->boxy', x, self.weight, y)
谢谢啦

**Comment by ljynlp** [comment]
$S = [X; 1]^\top U' [Y; 1]$，其中 $U' \in \mathbb{R}^{out, in + 1, in + 1}$ -> $S = X^\top U Y + X^\top W + W Y + b$，其中 $U \in \mathbb{R}^{out, in, in}, W \in \mathbb{R}^{out, in}, b \in \mathbb{R}^{in}$
$X$ 对应 { $s_1, \dots s_N$ }， $Y$ 对应 { $o_1, \dots, o_N$ }

**Comment by jingsongs** [comment]
大致明白了，谢谢哈

**Comment by JeremySun1224** [comment]
@ljynlp 您好 请问Biaffine层的构建中，为什么要cat`torch.cat((x, torch.ones_like(x[..., :1])), -1)`一个全1的张量呢？感谢
