### ISSUE TITLE
关于F1值的一点疑问

### ISSUE THREAD

**Issue by nlper01** [ljynlp/W2NER#65]
`best_f1 = 0

    best_test_f1 = 0

    for i in range(config.epochs):

        logger.info("Epoch: {}".format(i))

        trainer.train(i, train_loader)

        f1 = trainer.eval(i, dev_loader)

        test_f1 = trainer.eval(i, test_loader, is_test=True)

        if f1 > best_f1:

            best_f1 = f1

            best_test_f1 = test_f1

            trainer.save(config.save_path)

    logger.info("Best DEV F1: {:3.4f}".format(best_f1))

    logger.info("Best TEST F1: {:3.4f}".format(best_test_f1))

    trainer.load(config.save_path)

    trainer.predict("Final", test_loader, ori_data[-1])`
Best DEV F1和Best TEST F1取得是所有epoch中的最大值
那最后结果中的TEST Final的值是怎么计算的？没看明白

**Comment by ljynlp** [comment]
如果当前epoch dev f1大于之前的dev f1，则存储当前模型，并记录该f1分值，因此最后保存的模型即为dev f1表现最好的那个epoch的模型，最后加载该模型再对test set进行预测。
