### ISSUE TITLE
关于处理单个字作为实体

### ISSUE THREAD

**Issue by lzf00** [ljynlp/W2NER#73]
如果句子中的单个字作为实体，例如一句话中的第五个字 “ 爱”，作为一个实体，数据格式是不是这样，"index": [5, 5], "type": "动词"
然后此对关系THW为：（5，5），NNW则没有，不知道我的理解是否正确；

因为我的数据集中有一部分英文实体，我想把英文单词当作一个整体（字）来输入到模型中，不知道这样行不行？

**Comment by ljynlp** [comment]
理解是正确的，另外把英文单词当做一个字也是没问题的，只要分词正确就行
