### ISSUE TITLE
关于输出的分类结果标签和F1计算

### ISSUE THREAD

**Issue by lzf00** [ljynlp/W2NER#74]
1.如果我的数据集有两类实体，time，loc，那么模型的标签有四个 None，NNW，THW-time，THW-loc，模型是直接对这个四个标签进行分类，还是先分None，NNW，THW，如果是THW再去细分其类别？
2.Labels的F1计算是只看单个词对是否相同，Entity的F1计算是组成实体的所有词对都完成相同？

**Comment by ljynlp** [comment]
1.直接对4个标签分类
2.Labels的F1计算是只看单个词对是否相同，Entity F1是看解码出来的实体与gold实体是否相同

**Comment by lzf00** [comment]
好的，明白了，谢谢回复
