### ISSUE TITLE
中文数据集的配置

### ISSUE THREAD

**Issue by YoungErm** [ljynlp/W2NER#79]
您好，请问方便提供一下MSRA、OntoNote4和weibo的配置吗
这是我的邮箱: 1505340824@qq.com, 万分感激

**Comment by zdgithub** [comment]
@YoungErm 你好，方便提供一下一些MSRA、OntoNote4的下载地址吗？万分感谢

**Comment by YoungErm** [comment]
> @YoungErm 你好，方便提供一下一些MSRA、OntoNote4的下载地址吗？万分感谢

ontonotes这个w2ner的repo不是提供了下载地址吗
[MSRA](https://github.com/lemonhu/NER-BERT-pytorch/tree/master/data/msra)

**Comment by xingyue-333** [comment]
@YoungErm 您好  作者有提供给你配置文件吗？ 如果有的话能分享一下给我吗？这是我的邮箱2624647704@qq.com 谢谢

**Comment by Learning-0** [comment]
您好 作者有提供给你配置文件吗？ 如果有的话能分享一下给我吗？这是我的邮箱(2716727469@qq.com)感谢

**Comment by Wonderful23** [comment]
您好，我想复现一下中文MSRA、OntoNotes 4.0和Weibo数据集上结果，能否提供一下相关的config文件，谢谢。
这是我的邮箱：2596409301@qq.com

**Comment by ghost** [comment]
楼上的大佬们麻烦分享一份中文数据集的config 文件吧，谢谢！ nash1225@163.com
