### ISSUE TITLE
How to solve multiple overlapped?

### ISSUE THREAD

**Issue by tengerye** [ljynlp/W2NER#8]
Hi, if I have a sequence (A, B, C, D, E, F). The first entity is A, C, D, F and the second is B, C, E, F. With your strategy, there are two reasonable results for both entities. The first could be coded to ACDF or ACEF. While the second could be coded to BCDF or BCEF. 

My question is: how could your algorithm attack this situation?

**Comment by ljynlp** [comment]
This situation is really rare in the datasets and the algorithm will enumerate all possible entities. Actually, there is usually **ambiguity** in natural language when two entities share multiple discontinuous words. So, in this case, enumerating all of them is a reasonable and easy way.
