### ISSUE TITLE
Can't run example successfully

### ISSUE THREAD

**Issue by deeomnjobs** [ljynlp/W2NER#95]
![image](https://user-images.githubusercontent.com/114485859/233301960-03eb8d38-2223-47a3-9aa6-ff024368bfea.png)

**Comment by deeomnjobs** [comment]
u can solve this problem according to ucas010's problem.

**Comment by xingyue-333** [comment]
@deeomnjobs  不好意思   能问一下你是怎么解决这个问题的吗？我这也报错了

**Comment by 147258369Liyan** [comment]
> @deeomnjobs 不好意思 能问一下你是怎么解决这个问题的吗？我这也报错了

不好意思，想问一下，解决了吗，我这也是同样的问题
